name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: booklibrary_test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Ensure mocha permissions
      run: chmod +x ./node_modules/.bin/mocha

    - name: Create test database
      run: |
        sudo apt-get install -y mysql-client
        mysql -h 127.0.0.1 -uroot -proot -e "CREATE DATABASE IF NOT EXISTS booklibrary_test;"

    - name: Run tests
      env:
        DB_HOST: 127.0.0.1
        DB_USER: root
        DB_PASSWORD: root
        DB_NAME: booklibrary_test
        NODE_ENV: test
      run: |
        npm test

    - name: Stop MySQL service
      run: sudo service mysql stop

    - name: Stop Node.js server
      run: |
        lsof -i :3333 -t | xargs kill -9
